### ISSUE TITLE
Invert bufferline tab background

### ISSUE THREAD

**Issue by jfaz1** [catppuccin/helix#10]
Hey again!

Same issue as this one: https://github.com/catppuccin/wezterm/issues/8

Just for the new bufferline in `helix`:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/56184947/193390356-042ce65c-196a-4f6e-85b1-97172fb70977.png">

**Comment by Spaxly** [comment]
hmm, i'll look into this.

**Comment by Hidan0** [comment]
Hey! 
With the new bufferline in Helix 22.12 after generating the themes (from [c7c6ecb](https://github.com/catppuccin/helix/commit/c7c6ecb9f3f5f9b484d28ba5fd47ad95136bcb89)) this is what I got.

![image](https://user-images.githubusercontent.com/48904232/206789809-a812c717-5073-4410-bc6f-9a035bbb2777.png)
