### ISSUE TITLE
Inlay hints are unreadable

### ISSUE THREAD

**Issue by arexon** [catppuccin/helix#34]
Inlay hints are considerably hard to read as they blend in too much with the background

![problem](https://github.com/catppuccin/helix/assets/65680034/03edf826-d351-4ef7-82fd-1099a5b7cc4a)

## Possible solutions

1. Use `overlay1` for the foreground and `surface0` for the background
![solution_1](https://github.com/catppuccin/helix/assets/65680034/659de1a8-5155-449b-90f6-5f7457935f56)

2. Use `overlay0` for the foreground and `base` for the background
![solution_2](https://github.com/catppuccin/helix/assets/65680034/d073594d-b247-4381-a732-8791d3c473da)

**Comment by fnuttens** [comment]
Thanks for the alternatives, solution 2 looks much better IMO.
I hope the maintainers agree 😁

**Comment by ohxxm** [comment]
Implemented.
