### ISSUE TITLE
Theme doesn't seems so colorful as the repo screenshot

### ISSUE THREAD

**Issue by zoedsoupe** [catppuccin/helix#36]
i don't know if i need to activate a specific config on helix or if it is my terminal emulator, but catppuccin seems less colorful than the neovim version and this repo screenshots.

# Helix (wezterm) - catppuccin frappé
<img width="1051" alt="image" src="https://github.com/catppuccin/helix/assets/44469426/8ff15c7b-27ac-48ae-b8e3-d128f81b695c">

# Neovim (wezterm) - cappuccino frappé
<img width="1051" alt="image" src="https://github.com/catppuccin/helix/assets/44469426/9128ea18-2fd0-41de-9658-dff79f24090a">

**Comment by backwardspy** [comment]
hey, sorry for the delay on this. that is a *lot* of blue!

i've just made a small highlight change in #41 that i think really helps the legibility in elixir. let me know your thoughts! there may be other changes i can make to improve it further, but i want to chat with the others first to get consistency between neovim & vscode before bringing them into helix too.

thanks for raising this!

**Comment by zoedsoupe** [comment]
Thanks! there are some possible future increments that can be made specifically to Elixir (maybe Ruby and Clojure too) to use a different color for atoms (keywords or symbols) and so on.

it'll be awesome to see an improvement to this theme, that is my favourites one. 🐱💜

**Comment by backwardspy** [comment]
we're currently improving our style guide and just yesterday, coincidentally, we were deciding on a standard for atoms/symbols. expect to see that soon!
