### ISSUE TITLE
How to properly sync changes between helix-editor/helix and this repo?

### ISSUE THREAD

**Issue by NikitaRevenco** [catppuccin/helix#53]
Hi, so I changed the catppuccin theme in https://github.com/helix-editor/helix/pull/12167 and in https://github.com/helix-editor/helix/pull/12205

Should that change be copied here? Should future changes be made in both repos or how should it be done?

**Comment by uncenter** [comment]
Changes should ideally be made in this repository and then copied upstream to Helix's repository I think. If you want to raise a PR backporting new changes from upstream to this repository that would be great.

**Comment by NikitaRevenco** [comment]
Okay!
